/**
 * MRS Design System Theme Configuration
 * Material-UI v6.5.0 theme with centralized component overrides
 *
 * This theme uses:
 * 1. Design tokens generated by Style Dictionary (single source of truth)
 * 2. Component overrides for consistent styling across all components
 *
 * @version 0.12.0 - Migrated to 100% generated tokens (no theme.json dependency)
 * @see https://mui.com/material-ui/customization/theme-components/
 */

/// <reference path="../types/theme.d.ts" />

import type { Theme, ThemeOptions } from '@mui/material/styles';
import { createTheme } from '@mui/material/styles';

import { lightTokens, darkTokens, typographyTokens, shapeTokens } from './tokens-import';
import { styleCompositions } from './styleCompositions';

/**
 * Spacing function for MUI
 * Multiplies the base unit (8px) by the given factor
 */
const spacing = (factor: number): number => {
  const baseUnit = 8;
  return baseUnit * factor;
};

/**
 * Shared component overrides
 * These apply consistent styling across all components using theme tokens
 *
 * Benefits:
 * - Single place to manage component styles
 * - No need for sx prop overrides in individual components
 * - Consistent with MUI best practices
 * - 100% generated tokens (v0.12.0+)
 */
const getComponentOverrides = (mode: 'light' | 'dark'): ThemeOptions['components'] => {
  const modeTokens = mode === 'light' ? lightTokens : darkTokens;
  const shape = shapeTokens;
  const typography = typographyTokens;

  return {
    // =========================================================================
    // GLOBAL BASELINE
    // =========================================================================
    MuiCssBaseline: {
      styleOverrides: {
        body: {
        },
        // Apply Nunito font globally
        '*': {
          fontFamily: 'inherit',
        },
      },
    },

    // =========================================================================
    // BUTTONS
    // =========================================================================
    MuiButton: {
      defaultProps: {
        disableElevation: true,
      },
      styleOverrides: {
        root: {
          ...styleCompositions.button.base(),
          textTransform: 'none' as const,
        },
        sizeSmall: styleCompositions.button.sizes.small,
        sizeMedium: styleCompositions.button.sizes.medium,
        sizeLarge: styleCompositions.button.sizes.large,
      },
    },

    MuiIconButton: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiToggleButton: {
      styleOverrides: {
        root: {
          textTransform: 'none' as const,
        },
      },
    },

    MuiButtonGroup: {
      defaultProps: {
        disableElevation: true,
      },
      styleOverrides: {
        root: {
          borderRadius: shape.md,
        },
      },
    },

    MuiFab: {
      styleOverrides: {
        root: {
          borderRadius: shape.rounded,
          textTransform: 'none' as const,
        },
      },
    },

    // =========================================================================
    // INPUTS
    // =========================================================================
    MuiTextField: {
      defaultProps: {
        variant: 'outlined',
      },
      styleOverrides: {
        root: {
        },
      },
    },

    MuiOutlinedInput: {
      styleOverrides: {
        root: {
          borderRadius: shape.md,
        },
        notchedOutline: {
          borderColor: modeTokens.components.input.outlined.enabledBorder,
        },
      },
    },

    MuiFilledInput: {
      styleOverrides: {
        root: {
          backgroundColor: modeTokens.components.input.filled.enabledFill,
          borderRadius: `${shape.md}px ${shape.md}px 0 0`,
        },
      },
    },

    MuiInput: {
      styleOverrides: {
        root: {
        },
        underline: {
          '&:before': {
            borderBottomColor: modeTokens.components.input.standard.enabledBorder,
          },
        },
      },
    },

    MuiInputLabel: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiSelect: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiAutocomplete: {
      styleOverrides: {
        root: {
        },
      },
    },

    // =========================================================================
    // SELECTION CONTROLS
    // =========================================================================
    MuiCheckbox: {
      styleOverrides: {
        root: {
          '&.Mui-checked': {
            color: modeTokens.colors.primary.main,
          },
        },
      },
    },

    MuiRadio: {
      styleOverrides: {
        root: {
          '&.Mui-checked': {
            color: modeTokens.colors.primary.main,
          },
        },
      },
    },

    MuiSwitch: {
      styleOverrides: {
        root: {
          '& .MuiSwitch-switchBase.Mui-checked': {
            color: modeTokens.colors.primary.main,
          },
          '& .MuiSwitch-switchBase.Mui-checked + .MuiSwitch-track': {
            backgroundColor: modeTokens.colors.primary.main,
          },
        },
      },
    },

    // =========================================================================
    // CHIPS
    // =========================================================================
    MuiChip: {
      styleOverrides: {
        root: {
          ...styleCompositions.chip.base(),
        },
        outlined: {
          borderColor: modeTokens.components.chip.defaultEnabledBorder,
        },
        deleteIcon: {
          color: modeTokens.components.chip.defaultCloseFill,
        },
      },
    },

    // =========================================================================
    // ALERTS & FEEDBACK
    // =========================================================================
    MuiAlert: {
      styleOverrides: {
        root: {
          borderRadius: `${shape.md}px`,
        },
        // Filled variants
        filledError: {
          backgroundColor: modeTokens.components.alert.error.filled.background,
          color: modeTokens.components.alert.error.filled.foreground,
        },
        // Outlined variants
        outlinedError: {
          backgroundColor: modeTokens.components.alert.error.outlined.background,
          color: modeTokens.components.alert.error.outlined.foreground,
          borderColor: modeTokens.components.alert.error.outlined.border,
        },
        // Standard variants
        standardError: {
          backgroundColor: modeTokens.components.alert.error.standard.background,
          color: modeTokens.components.alert.error.standard.foreground,
        },
      },
    },

    MuiSnackbar: {
      styleOverrides: {
        root: {
        },
      },
    },

    // =========================================================================
    // SURFACES
    // =========================================================================
    MuiPaper: {
      styleOverrides: {
        root: {
        },
        rounded: {
          borderRadius: shape.md,
        },
        elevation0: {
          backgroundColor: modeTokens.components.paper.elevation0,
        },
        elevation1: {
          backgroundColor: modeTokens.components.paper.elevation1,
        },
        elevation2: {
          backgroundColor: modeTokens.components.paper.elevation2,
        },
      },
    },

    MuiCard: {
      styleOverrides: {
        root: {
          borderRadius: shape.lg,
        },
      },
    },

    MuiDialog: {
      styleOverrides: {
        paper: {
          borderRadius: shape.lg,
        },
      },
    },

    MuiDrawer: {
      styleOverrides: {
        paper: {
        },
      },
    },

    MuiAppBar: {
      styleOverrides: {
        root: {
        },
      },
    },

    // =========================================================================
    // TABLES
    // =========================================================================
    MuiTable: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiTableCell: {
      styleOverrides: {
        root: {
          borderBottomColor: modeTokens.components.table.border,
        },
        head: {
          fontWeight: typography.fontWeightMedium,
        },
      },
    },

    // =========================================================================
    // LISTS & MENUS
    // =========================================================================
    MuiList: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiListItem: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiListItemButton: {
      styleOverrides: {
        root: {
          ...styleCompositions.listItem.base(),
          '&.Mui-selected': {
            backgroundColor: modeTokens.colors.action.selected,
            fontWeight: typography.fontWeightSemiBold,
          },
          '&.Mui-selected:hover': {
            backgroundColor: modeTokens.colors.action.hover,
          },
          '&:hover': {
            backgroundColor: modeTokens.colors.action.hover,
          },
        },
      },
    },

    MuiListItemText: {
      styleOverrides: {
        primary: {
        },
        secondary: {
        },
      },
    },

    MuiMenu: {
      styleOverrides: {
        paper: {
          borderRadius: shape.md,
        },
      },
    },

    MuiMenuItem: {
      styleOverrides: {
        root: {
        },
      },
    },

    // =========================================================================
    // NAVIGATION
    // =========================================================================
    MuiTabs: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiTab: {
      styleOverrides: {
        root: {
          textTransform: 'none' as const,
        },
      },
    },

    MuiBreadcrumbs: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiPagination: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiStepper: {
      styleOverrides: {
        root: {
        },
      },
    },

    // =========================================================================
    // TYPOGRAPHY
    // =========================================================================
    MuiTypography: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiLink: {
      styleOverrides: {
        root: {
        },
      },
    },

    // =========================================================================
    // DATA DISPLAY
    // =========================================================================
    MuiAvatar: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiBadge: {
      styleOverrides: {
        badge: {
        },
      },
    },

    MuiTooltip: {
      styleOverrides: {
        tooltip: {
        },
      },
    },

    MuiDivider: {
      styleOverrides: {
        root: {
          borderColor: modeTokens.colors.divider,
        },
      },
    },

    // =========================================================================
    // FORMS
    // =========================================================================
    MuiFormControlLabel: {
      styleOverrides: {
        label: {
        },
      },
    },

    MuiFormHelperText: {
      styleOverrides: {
        root: {
        },
      },
    },

    MuiFormLabel: {
      styleOverrides: {
        root: {
        },
      },
    },

    // =========================================================================
    // PROGRESS
    // =========================================================================
    MuiLinearProgress: {
      styleOverrides: {
        root: {
          borderRadius: shape.sm,
        },
      },
    },

  };
};

/**
 * Light theme configuration
 * Uses 100% generated tokens from Style Dictionary
 */
export const lightTheme: Theme = createTheme({
  palette: {
    mode: 'light',
    primary: lightTokens.colors.primary,
    secondary: lightTokens.colors.secondary,
    error: lightTokens.colors.error,
    background: lightTokens.colors.background,
    text: lightTokens.colors.text,
    action: lightTokens.colors.action,
    divider: lightTokens.colors.divider,
    _components: lightTokens.components,
  },
  typography: {
    ...typographyTokens,
  },
  shape: {
    ...shapeTokens,
  },
  spacing,
  components: getComponentOverrides('light'),
});

/**
 * Dark theme configuration
 * Uses 100% generated tokens from Style Dictionary
 */
export const darkTheme: Theme = createTheme({
  palette: {
    mode: 'dark',
    primary: darkTokens.colors.primary,
    secondary: darkTokens.colors.secondary,
    error: darkTokens.colors.error,
    background: darkTokens.colors.background,
    text: darkTokens.colors.text,
    action: darkTokens.colors.action,
    divider: darkTokens.colors.divider,
    _components: darkTokens.components,
  },
  typography: {
    ...typographyTokens,
  },
  shape: {
    ...shapeTokens,
  },
  spacing,
  components: getComponentOverrides('dark'),
});

/**
 * Default theme export (light mode)
 */
export const theme = lightTheme;

/**
 * Export both themes for theme switching
 */
export default {
  light: lightTheme,
  dark: darkTheme,
};
